#!/usr/bin/env python
"""Single source of truth for rfcnt docstrings.

Reads docstrings/*.txt and:
  1. Writes src/docstrings_generated.hpp for use in rfcnt.cpp (PYBIND11_MODULE).
  2. Rewrites the docstring of each matching function *in place* inside rfcnt.pyi,
     leaving the hand-written signature (types, defaults, Optional/Union) untouched.

Usage:
    python tools/sync_docstrings.py          # regenerate in place
    python tools/sync_docstrings.py --check  # exit 1 if regenerating would change anything (CI)
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCSTRING_DIR = ROOT / "docstrings"
CPP_HEADER = ROOT / "src" / "docstrings_generated.hpp"
PYI_FILE = ROOT / "rfcnt.pyi"

# function name -> C++ constant name used in PYBIND11_MODULE
CPP_CONST_NAMES = {
    "rfc": "RFC_DOC",
    "damage_from_rp": "DAMAGE_FROM_RP_DOC",
    "at_transform": "AT_TRANSFORM_DOC",
}


def load_docstrings() -> dict[str, str]:
    docs = {}
    for txt_file in sorted(DOCSTRING_DIR.glob("*.txt")):
        docs[txt_file.stem] = txt_file.read_text(encoding="utf-8")
    return docs


def render_cpp_header(docs: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by tools/sync_docstrings.py — DO NOT EDIT BY HAND.",
        "// Source of truth: docstrings/*.txt",
        "#pragma once",
        "",
    ]
    for name, text in docs.items():
        if name not in CPP_CONST_NAMES:
            continue
        const_name = CPP_CONST_NAMES[name]
        # delimiter chosen to be extremely unlikely to collide with docstring content
        lines.append(f'inline constexpr const char* {const_name} = R"rfcnt_doc(')
        lines.append(text.rstrip("\n"))
        lines.append(')rfcnt_doc";')
        lines.append("")
    return "\n".join(lines)


def render_pyi(docs: dict[str, str]) -> str:
    source = PYI_FILE.read_text(encoding="utf-8")
    tree = ast.parse(source)

    edits: list[tuple[int, int, str]] = []  # (char_start, char_end, replacement)
    line_starts = [0]
    for line in source.splitlines(keepends=True):
        line_starts.append(line_starts[-1] + len(line))

    def char_offset(lineno: int, col: int) -> int:
        return line_starts[lineno - 1] + col

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef) or node.name not in docs:
            continue
        if not node.body:
            continue
        first = node.body[0]
        is_docstring = (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
        )
        if not is_docstring:
            # No existing docstring on this overload/def — don't invent placement, skip.
            continue

        # docs[node.name] already includes the trailing "\n<indent>" that precedes
        # the closing triple-quote (that whitespace is part of the string literal
        # itself in the original source) — don't add indentation again here.
        new_text = docs[node.name]
        replacement = f'r"""{new_text}"""'

        start = char_offset(first.lineno, first.col_offset)
        end = char_offset(first.end_lineno, first.end_col_offset)
        edits.append((start, end, replacement))

    for start, end, replacement in sorted(edits, reverse=True):
        source = source[:start] + replacement + source[end:]

    return source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                         help="exit 1 if files would change, without writing")
    args = parser.parse_args()

    docs = load_docstrings()
    new_cpp = render_cpp_header(docs)
    new_pyi = render_pyi(docs)

    changed = []
    if not CPP_HEADER.exists() or CPP_HEADER.read_text(encoding="utf-8") != new_cpp:
        changed.append(CPP_HEADER)
    if PYI_FILE.read_text(encoding="utf-8") != new_pyi:
        changed.append(PYI_FILE)

    if args.check:
        if changed:
            print("Docstrings out of sync in:", ", ".join(str(p) for p in changed))
            print("Run: python tools/sync_docstrings.py")
            return 1
        print("Docstrings in sync.")
        return 0

    CPP_HEADER.parent.mkdir(parents=True, exist_ok=True)
    CPP_HEADER.write_text(new_cpp, encoding="utf-8")
    PYI_FILE.write_text(new_pyi, encoding="utf-8")
    print(f"Synced {len(docs)} docstring(s) -> {CPP_HEADER}, {PYI_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
